### PR TITLE
Include php5-intl

### PR DESCRIPTION
**Pull request by jbrooksuk**

### CODE REVIEW

**Comment by jbrooksuk** [comment]
No `NumberFormatter` then :(

**Comment by taylorotwell** [comment]
PHP 5 isn't supported by settler anymore.

**Comment by ssx** [comment]
There's a php7.0-intl package as well @jbrooksuk

**Comment by jbrooksuk** [comment]
Lol, I don't know what happened when I tried to update my fork to the latest version, it must've failed or something. Ah well.

**Pull request closed without merging**
