### PR TITLE
.composer folder not created fix

### PR DESCRIPTION
**Pull request by ibrahimmomani**
Make sure that .composer folder exist.

### CODE REVIEW

**Comment by taylorotwell** [comment]
Why would it not be created after installing Composer?

**Comment by ibrahimmomani** [comment]
For some reason now composer is uses .config/composer/ instead of .composer, I didn't looked it up but in my machine i use .config/composer/.

**Comment by taylorotwell** [comment]
So what does this addition actually fix? Sorry, trying to understand. If Composer uses a new directory why do we create this one?

**Comment by ibrahimmomani** [comment]
well you may don't have this issue on OSX but with ubuntu the default home for composer is .config/composer, and i used to have .composer as COMPOSER_HOME dir and most php guys still do.

**Comment by andrewhood125** [comment]
I did these steps and was not able to reproduce this. 
  - `vagrant box add bento/ubuntu-14.04`
  - Opened virtualbox and imported the box. 
  - `sudo apt-get update`
  - `sudo apt-get install curl php5-cli`
  - `curl -sS https://getcomposer.org/installer | php`

screen shot 2016-03-24 at 8 04 58 pm

**Comment by andrewhood125** [comment]
Tried with `php7.0-cli` too. 
screen shot 2016-03-24 at 8 24 58 pm

How are you getting `${COMPOSER_HOME}` to be `${HOME}/.config/.composer`?

**Comment by ibrahimmomani** [comment]
Yes, you are right with this way installing composer, but did you try to use the provision.sh?
In other words try to create a vagrant machine using the current provisioning scripts

here is the output of the console when it is downloading and installing composer:

> ==> default: All settings correct for using Composer
> ==> default: Downloading...
> ==> default: 
> ==> default: Composer successfully installed to: /home/vagrant/composer.phar
> ==> default: 
> ==> default: Use it: php composer.phar
> ==> default: 
> ==> default: PATH="/home/vagrant/.composer/vendor/bin:$PATH"
> ==> default: Changed current directory to /home/vagrant/.config/composer

and after installing ssh to the new machine
screenshot 2016-03-25 08 25 37

and ls to your .config
screenshot 2016-03-25 08 32 11

Don't know if this worth checking or not but i saw a lot of my friends who are using homestead are facing a problem that their composer global are not working, but the thing they don't know that the home_dir path is set to .composer in .profile instead of .config/composer and thats why it seems to be broken to them.

**Comment by ibrahimmomani** [comment]
what i think now is changing the line from
`printf "\nPATH=\"/home/vagrant/.composer/vendor/bin:\$PATH\"\n" | tee -a /home/vagrant/.profile`
to
`printf "\nPATH=\"/home/vagrant/.config/composer/vendor/bin:\$PATH\"\n" | tee -a /home/vagrant/.profile`

this is better i think !!

**Comment by andrewhood125** [comment]
Hmm you're right. How about this: 
screen shot 2016-03-25 at 12 19 53 am

```
printf "\nPATH=\"$(composer config -g home 2>/dev/null)/vendor/bin:\$PATH\"\n" | tee -a /home/vagrant/.profile
```

**Comment by alexbowers** [comment]
I just had this issue, where i had to change the path in the ~/.profile

**Comment by ibrahimmomani** [comment]
@alexbowers in your .profile find the line 
`PATH="/home/vagrant/.composer/vendor/bin:$PATH"`

replace it with
`PATH="/home/vagrant/.config/composer/vendor/bin:$PATH"`

**Comment by alexbowers** [comment]
Yeah i've fixed, just pointing out that it is an issue and needs merging in :)

**Comment by andrewhood125** [comment]
Looks good to me.

**Pull request merged**
