### PR TITLE
Replacing sendmail with mhsendmail for php

### PR DESCRIPTION
**Pull request by mroedel**
Installed mhsendmail & set it as sendmail_path

### CODE REVIEW

**Comment by svpernova09** [comment]
What is the advantage of this when currently you can just set the STMP port in your `.env` to the port mailhog is expecting?

**Comment by mroedel** [comment]
since homestead is not only for laravel it might be a good way for accessing mailhog with other platforms

**Comment by svpernova09** [comment]
Most PHP applications (especially modern full stack frameworks) are either going to use an API for sending mail or using SMTP directly. What's the benefit of this when Mailhog already gives us the SMTP server?

Not against the change, just want to understand what we're gaining.

**Comment by taylorotwell** [comment]
Closing pending inactivity.

**Pull request closed without merging**
