### PR TITLE
✨ 💡 Add and configure PHP 5.6, 7.0, and 7.1

### PR DESCRIPTION
**Pull request by svpernova09**

### CODE REVIEW

**Comment by mortscode** [comment]
Do you guys have an article that explains how to use different PHP versions per site? 

I'm trying 
```
Sites:
    - map: test.dev
       to: /path/to/public
       php: "5.6"
```
but it's still showing as PHP 7.1 when i run `phpinfo()`

**Comment by svpernova09** [comment]
@mortscode 

The docs have been updated: https://laravel.com/docs/5.4/homestead#multiple-php-versions

**Comment by mortscode** [comment]
Do I need to checkout Homestead 6.x in my `~/Homestead` directory?

Your docs still say:
```
// Clone the desired release...
git checkout v5.4.0
```

**Comment by svpernova09** [comment]
yes, it's impossible to keep the docs updated >.< Always checkout the latest tagged release: https://github.com/laravel/homestead/releases

**Comment by mortscode** [comment]
Awesome. 

Thanks @svpernova09. I'll give it a go.

**Comment by mortscode** [comment]
I'm not too worried about it because i'm using 7.0 or 7.1 pretty exclusively now, but i'm getting an error in my homestead provision for 5.6:

```
Job for php5.6-fpm.service failed because the control process exited with error code. See "systemctl status php5.6-fpm.service" and "journalctl -xe" for details.
```

Any thoughts?

**Comment by svpernova09** [comment]
Hrm, their may be a bug in the version, someone in slack was having a similar issue. can you fill out a new issue: https://github.com/laravel/homestead/issues/new and I'll see if I can recreate

**Comment by dmyers** [comment]
It looks like php 5.6 is missing mcrypt.

@mortscode Can you try removing your variables? I removed mine and that error went away for me.

**Comment by svpernova09** [comment]
@dmyers nice catch, fixed via https://github.com/laravel/settler/pull/115

**Comment by mortscode** [comment]
what @svpernova09 said.

**Pull request merged**
