### PR TITLE
Include prestissimo for parallel composer downloads

### PR DESCRIPTION
**Pull request by deviantintegral**
Includes https://github.com/hirak/prestissimo which is a very nice performance improvement for composer downloads.

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks!

**Comment by browner12** [comment]
Do you guys understand how this package works? I don't fully comprehend how this works, so it makes me a little nervous to allow a package other than Composer to be downloading files for our applications.

Am I being overly cautious here?

**Comment by svpernova09** [comment]
@browner12 

AFAIK it just caches the dependency calculations which means we don't crunch the version matrix every time, which is where the speed increase comes from. There's nothing it can do to intercept or change package downloads. (unless I'm just glossing over something)

**Comment by browner12** [comment]
Ok. I was under the impression based on the title of this PR that normal composer downloads one at a time, while this package allowed you to run downloads in parallel, which made me think it was tweaking how the downloads are run.

I will try and dig into the source a little more to make sure this is right.

@deviantintegral do you have any insight on this?

**Comment by deviantintegral** [comment]
It does parallelize downloads by prefetching the dists into Composer's cache: https://github.com/hirak/prestissimo/blob/master/src/Prefetcher.php. There's no dependency resolution caching (since that's not really possible during update, and install is handled by the lock file). On the one hand, you're right in that it's a composer plugin so it _can_ do anything during the composer process. However, as written today the actual installation and verification is all handled by Composer - it sees the files in it's cache as if a prior command had downloaded them.

The plugin has 5M downloads / 4.6K stars, so I'd think is one of the more tested / used packages Homestead currently ships.

**Comment by browner12** [comment]
thanks for that info.

I know I'm probably being overly paranoid about this, just want to make sure we don't expose our users to any unnecessary risk.

**Pull request merged**
