### PR TITLE
Load TimeZone tables in MySQL to enable TZ support

### PR DESCRIPTION
**Pull request by mikebronner**
Moved pull request to its own branch

### CODE REVIEW

**Comment by taylorotwell** [comment]
Can you give more info on what this does? Thanks

**Comment by mikebronner** [comment]
Hi Taylor,

Loading the timezone tables in MySQL allows for timezone calculations within mysql queries, like using CONVERT_TZ to convert dates and timestamps to different timezones, as well as other timezone-aware functions. For example:

**Comment by taylorotwell** [comment]
Can you move this operation to be more close to other MySQL related things?

**Comment by mikebronner** [comment]
Did you still want me to move the lines? :)

**Comment by taylorotwell** [comment]
I already did. Thanks

**Pull request merged**
