### PR TITLE
Upgrade mysql version to 5.7

### PR DESCRIPTION
**Pull request by alibo**
MySQL 5.7 stable version (GA - 5.7.9) is released last month (2015-10-21) and has a lot of new features and improvements such as:
- JSON support
- GIS features (e.g. InnoDB spatial indexes, GeoJSON and GeoHash functions)

*More info -> [Complete list of new features in MySQL 5.7](http://www.thecompletelistoffeatures.com/)*

### CODE REVIEW

**Comment by dbpolito** [comment]
:+1:

**Comment by dmyers** [comment]
Nice work! I was about to work on this and you beat me too it. :+1:

**Comment by taylorotwell** [comment]
http://d.pr/i/16k3m/1Fho2xBh

Breaks Things. Reverted. Please test your PRs.

**Comment by dmyers** [comment]
Yeah I just upgraded to the latest and got the same thing:
```
==> default: mysql: [Warning] Using a password on the command line interface can be insecure.
==> default: ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by taylorotwell** [comment]
@alibo did you test this at all?

**Comment by dmyers** [comment]
@taylorotwell The 5.7 [changelog](http://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-6.html) shows `mysql_install_db` command which was changed to `mysqld` and requires the flag [` --initialize-insecure`](https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_initialize-insecure).

**Comment by taylorotwell** [comment]
Where are we calling mysql_install_db?

**Comment by dmyers** [comment]
@taylorotwell Oops yeah you're right I don't see any explicit calls to it, though something internal has to initialize the MySQL data directories I thought.

**Comment by alibo** [comment]
@taylorotwell Yes, of course, 3 times! (manually on bento/ubuntu-14.0.4, provisioning by vagrant (only mysql + whole provision.sh) and all 3 times it works for me:
http://d.pr/i/IPUJ
http://d.pr/i/5iyN
http://d.pr/i/1d48D

@dmyers Thank you for your great job :) :+1: ( #59 )

**Pull request merged**
