### PR TITLE
Add pv to the homestead box

### PR DESCRIPTION
**Pull request by thecrypticace**
Does what it says on the tin.

edit: This is for progress reporting between pipes.

### CODE REVIEW

**Comment by ssx** [comment]
@thecrypticace: why would this serve the needs of the majority?

**Comment by thecrypticace** [comment]
This came about because of this: https://github.com/laravel/homestead/pull/542

The short of it is that we can offer progress reporting long running tasks which run through unix pipes. It's quite common to use this command with utilities like `dd` as well (though for most that one doesn't get used in a Homestead box at least)

**Comment by ssx** [comment]
makes plenty of sense now! pv is one of my favourite commands :)

**Comment by svpernova09** [comment]
Thanks!

**Pull request merged**
