### PR TITLE
Fix bug that causes MySQL to disallow remote connections.

### PR DESCRIPTION
**Pull request by kevinsmith**
ref: https://github.com/laravel/homestead/pull/506#issuecomment-284782441

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks for the PR!

**Comment by kevinsmith** [comment]
Happy to help!

**Comment by kevinsmith** [comment]
Hey Joe, would you mind releasing v0.3.5 of the box? Looks like Vagrant won't let me download it while it's unreleased. Thanks!

**Comment by svpernova09** [comment]
@kevinsmith Was waiting for the box to finish uploading, it should be released now: https://atlas.hashicorp.com/Svpernova09/boxes/homestead-legacy/versions/0.3.5

**Comment by kevinsmith** [comment]
Sorry, got a little eager there. Thanks!

**Pull request merged**
