### PR TITLE
Update the volume group to homestead-vg

### PR DESCRIPTION
**Pull request by deviantintegral**
Resolves https://github.com/laravel/homestead/issues/1112

### CODE REVIEW

**Comment by svpernova09** [comment]
Thanks!

**Comment by m4olivei** [comment]
Hey there 👋 . Any idea when this will be rolled into a release?

**Comment by svpernova09** [comment]
> Hey there 👋 . Any idea when this will be rolled into a release?

Since Ubuntu 19.04 has been released my focus will be on v8. We may not see another 7.x release.

**Comment by m4olivei** [comment]
Gotcha. OK, I see now that this is a simple change to make on a per-instance basis for now. Thanks!

**Pull request merged**
