### PR TITLE
Parallels

### PR DESCRIPTION
**Pull request by alexbowers**

### CODE REVIEW

**Comment by alexbowers** [comment]
@svpernova09

**Comment by svpernova09** [comment]
@alexbowers Who can I contact at Parallels for a license? (Or to see if that offer is still on the table)

You can email me at first @ first + last dot m e
Freenode: joepferguson

**Comment by alexbowers** [comment]
@legal90 was the person last time

https://github.com/laravel/settler/pull/73

That email is cryptic.

Joe Ferguson?

**Comment by svpernova09** [comment]
Yep!

**Comment by legal90** [comment]
@alexbowers Thanks for pinging me. I've sent a key to @svpernova09.

**Comment by alexbowers** [comment]
Great, thank you.

**Comment by alexbowers** [comment]
Great, i'll note on my boxes to go with the actual official one.

**Comment by svpernova09** [comment]
Box has finished uploading and should be available.

**Pull request merged**
