### PR TITLE
Changing MySQL to MariaDB

### PR DESCRIPTION
**Pull request by dbpolito**
There are several reasons to move to MariaDB, https://seravo.fi/2015/10-reasons-to-migrate-to-mariadb-if-still-using-mysql

Maybe it's a good idea we encourage laravel community to move too! =)

### CODE REVIEW

**Comment by taylorotwell** [comment]
Not sure we want to make this change right now but will keep it in mind in the future.

**Comment by dbpolito** [comment]
What if we create a MariaDB version as you did for php 7?

**Comment by andrewhood125** [comment]
I hope we do make this change eventually as officially MySQL is not free for closed source projects. 

>For OEMs, ISVs, VARs and Other Distributors of Commercial Applications:

>OEMs (Original Equipment Manufacturers), ISVs (Independent Software Vendors), VARs (Value Added Resellers) and other distributors that combine and distribute commercially licensed software with MySQL software and do not wish to distribute the source code for the commercially licensed software under version 2 of the GNU General Public License (the "GPL") must enter into a commercial license agreement with Oracle.

http://www.mysql.com/about/legal/licensing/oem/

**Comment by dbpolito** [comment]
If this doesn't get merged, i will probably create a fork and use it for me and my team... I saw on lot of places this is the time for moving, as probably the next versions of maria will have some breaking changes, it's easier to do the move now then later...

**Comment by taylorotwell** [comment]
That would be true if you were going to bundle up and ship (“combine and distirbute) MySQL with your non-free application. However, that does not apply to a SaaS application.

**Comment by andrewhood125** [comment]
Oh that's the first time I've heard that interpretation do you have a source @taylorotwell? Would be great if that's true. :tada:

**Comment by taylorotwell** [comment]
That’s the interpretation of all GPL licensed products in relation to SaaS that I have ever heard or read.

**Comment by dbpolito** [comment]
The reason of my move is not only related to the license but all new features and performance improvements, MariaDB is moving faster than MySQL... it's open source and no breaking changes for now, so it's a smooth transition...

**Comment by dmyers** [comment]
@dbpolito MySQL 5.7 came out recently and has a lot of improvements like JSON data types, 3x more performance, and more GIS support.

https://www.oracle.com/corporate/pressrelease/mysql-5-7-ga-101915.html

**Comment by dbpolito** [comment]
Indeed, looks really nice!

**Pull request closed without merging**
