### PR TITLE
Fix issues related to blackfire and hhvm

### PR DESCRIPTION
**Pull request by joshfng**
The issue with blackfire was related to trying to `curl` the apt signing key before `curl` was actually installed.

The issue with HHVM was the Ubuntu 'codename' was no longer 'trusty` so the wrong deb was being pulled. I have verfied that hhvm does install correctly and start up.

Log snippet of successful build below:

blackfire:
```shell
==> default: The following NEW packages will be installed:
==> default:   blackfire-agent blackfire-php
==> default: 0 upgraded, 2 newly installed, 0 to remove and 4 not upgraded.
==> default: Need to get 4,443 kB of archives.
==> default: After this operation, 14.5 MB of additional disk space will be used.
==> default: Get:1 http://packages.blackfire.io/debian/ any/main blackfire-agent amd64 0.21.2 [3,745 kB]
==> default: Get:2 http://packages.blackfire.io/debian/ any/main blackfire-php amd64 0.20.6 [698 kB]
==> default: dpkg-preconfigure: unable to re-open stdin: No such file or directory
==> default: Fetched 4,443 kB in 9s (451 kB/s)
==> default: Selecting previously unselected package blackfire-agent.
==> default: (Reading database ... 44686 files and directories currently installed.)
==> default: Preparing to unpack .../blackfire-agent_0.21.2_amd64.deb ...
==> default: Unpacking blackfire-agent (0.21.2) ...
==> default: Selecting previously unselected package blackfire-php.
==> default: Preparing to unpack .../blackfire-php_0.20.6_amd64.deb ...
==> default: Unpacking blackfire-php (0.20.6) ...
==> default: Processing triggers for man-db (2.7.0.2-2) ...
==> default: Processing triggers for ureadahead (0.100.0-16) ...
==> default: Setting up blackfire-agent (0.21.2) ...
==> default: creating blackfire system user
==> default:
==> default:
==> default: 	ADDITIONAL STEP REQUIRED!
==> default:
==> default: 	If this is a new install please run:
==> default:
==> default: 	sudo blackfire-agent --register
==> default: 	sudo /etc/init.d/blackfire-agent start
==> default: Setting up blackfire-php (0.20.6) ...
==> default: blackfire-php install completed.
```

hhvm
```shell
==> default: Setting up hhvm (3.5.1~utopic) ...
==> default: ********************************************************************
==> default: * HHVM is installed.
==> default: * 
==> default: * Running PHP web scripts with HHVM is done by having your webserver talk to HHVM
==> default: * over FastCGI. Install nginx or Apache, and then:
==> default: * $ sudo /usr/share/hhvm/install_fastcgi.sh
==> default: * $ sudo /etc/init.d/hhvm restart
==> default: * (if using nginx)  $ sudo /etc/init.d/nginx restart
==> default: * (if using apache) $ sudo /etc/init.d/apache restart
==> default: * 
==> default: * Detailed FastCGI directions are online at:
==> default: * https://github.com/facebook/hhvm/wiki/FastCGI
==> default: * 
==> default: * If you're using HHVM to run web scripts, you probably want it to start at boot:
==> default: * $ sudo update-rc.d hhvm defaults
==> default: * 
==> default: * Running command-line scripts with HHVM requires no special setup:
==> default: * $ hhvm whatever.php
==> default: * 
==> default: * You can use HHVM for /usr/bin/php even if you have php-cli installed:
==> default: * $ sudo /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60
==> default: ********************************************************************
==> default: Setting up libpaper-utils (1.1.24+nmu2ubuntu3) ...
==> default: Processing triggers for libc-bin (2.19-10ubuntu2.3) ...
==> default:  * Restarting nginx nginx
==> default:    ...done.
==> default: php5-fpm stop/waiting
==> default: php5-fpm start/running, process 3135
```

### CODE REVIEW

**Comment by taylorotwell** [comment]
Thanks for researching this. <3

**Comment by joshfng** [comment]
Have the new boxes been built/uploaded?

**Comment by taylorotwell** [comment]
I've built them but need to test. Have you tested both?

**Comment by joshfng** [comment]
Yep both providers appear to be working correctly.

**Pull request merged**
